name: Main
on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install npm@7
        run: npm i -g npm@7
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build -- -p never
      - name: Archive dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install npm@7
        run: npm i -g npm@7
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
