name: Release
on:
  create:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install npm@7
        run: npm i -g npm@7
      - name: Install snapcraft
        run: snap install snapcraft --classic
        if: ${{ matrix.os == 'ubuntu_latest' }}
      - name: Login to snapcraft
        run: echo "$SNAP_TOKEN" | snapcraft login --with -
        if: ${{ matrix.os == 'ubuntu_latest' }}
        env:
          SNAP_TOKEN: ${{ secrets.SNAP_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Publish
        run: npm run build -- -p always -c.snap.publish.channels=stable
        env:
          GH_TOKEN: ${{ secrets.RELEASES_GITHUB_TOKEN }}
